name: PGM
api-version: 1.21.1
description: ${description}
main: ${mainClass}
version: ${version} (git-${commitHash})
website: ${url}
bootstrapper: tc.oc.pgm.platform.modern.PgmBootstrap

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: true